CREATE TABLE HISTRNSHDR
(
  `HISHDRID` int(11) NOT NULL AUTO_INCREMENT,
  `HISHDRTBLNO` int(3) NOT NULL,
  `HISTRNCUS` int(7) NOT NULL,
  `HISHDRTOTALPRICE` int(7) DEFAULT NULL,
  `HISTRNSTAT` varchar(6) NOT NULL DEFAULT 'OPEN',
  `HISHDRRESPON` int(11) NOT NULL,
  `HISHDRTIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `HISHDRTIMEEAT` varchar(40) NOT NULL

PRIMARY KEY (HISHDRID)
)